In [53]:
import pandas as pd
import numpy as np


# Importación de los datos

In [103]:
# Importamos el excel como un DataFrame
Hospital = pd.read_excel(r'C:\Users\Usuario\proyectos PY\SOY HENRY\Bootcamp\M6\Proyecto Integrador\Propuesta 1\BBDD_Hospitalización.xlsx')
# Creamos copia para modificar y tener un respaldo original de comparación
HospitalOk = Hospital.copy()

c:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


A continuación se hace una primera limpieza, borrando registros vacíos y cambiando nombre de columnas

In [104]:
# Eliminamos registros completamente vacíos
HospitalOk.dropna(how='all', inplace=True)

In [105]:
# Cambiamos nombre a columnas, para quitar tildes, normalizar estilos y achicar los nombres extensos

HospitalOk.rename(columns={HospitalOk.columns[2]: 'HOSPITALIZACION ULTIMO MES'}, inplace=True)
HospitalOk.rename(columns={HospitalOk.columns[6]: 'ANTIBIOTICO UTILIZADO'}, inplace=True)
HospitalOk.rename(columns={HospitalOk.columns[7]: 'MUESTRAS TOMADAS'}, inplace=True)
HospitalOk.rename(columns={HospitalOk.columns[9]: 'ENFERMEDAD CRONICA PULMONAR OBSTRUCTIVA'}, inplace=True)
HospitalOk.rename(columns={HospitalOk.columns[11]: 'COMPLICACION INFECCIOSA POST BIOPSIA'}, inplace=True)
HospitalOk.rename(columns={HospitalOk.columns[19]: 'DIAS HOSPITALIZACION UPC'}, inplace=True)


# Análisis y visualización estadística de cada columna.
Cuando vemos que el count es menor a 568 es porque hay valores NaN.
Estos valores deben ser np.nan

A continuación también corroboramos que los valores únicos correspondan a categorías realmente distintas
y no sean errores de tipeo.

En caso de encontar errores de tipeo serán corregidos

In [125]:
print(HospitalOk['EDAD'].unique())
#print(HospitalOk['EDAD'].value_counts())
print(HospitalOk['EDAD'].count())
print(HospitalOk['EDAD'].describe())

[ 53.  56.  57.  55.  67.  69.  44.  54.  68.  43.  65.  62.  71.  64.
  77.  75.  73.  63.  66.  84.  42.  61.  47.  48.  49.  81.  52.  74.
  70.  58.  59.  60.  50. 143. 151.  76.  78.  46.  51.  79.  39.  72.
  80.  45.  82.]
568
count    568.000000
mean      63.882042
std        9.281517
min       39.000000
25%       59.000000
50%       64.000000
75%       69.000000
max      151.000000
Name: EDAD, dtype: float64


In [124]:
print(HospitalOk['DIABETES'].unique())
print(HospitalOk['DIABETES'].value_counts())
print(HospitalOk['DIABETES'].count())
print(HospitalOk['DIABETES'].describe())

['NO' 'SI']
DIABETES
NO    505
SI     63
Name: count, dtype: int64
568
count     568
unique      2
top        NO
freq      505
Name: DIABETES, dtype: object


In [123]:
print(HospitalOk['HOSPITALIZACION ULTIMO MES'].unique())
print(HospitalOk['HOSPITALIZACION ULTIMO MES'].value_counts())
print(HospitalOk['HOSPITALIZACION ULTIMO MES'].count())
print(HospitalOk['HOSPITALIZACION ULTIMO MES'].describe())

['NO' 'SI']
HOSPITALIZACION ULTIMO MES
NO    563
SI      5
Name: count, dtype: int64
568
count     568
unique      2
top        NO
freq      563
Name: HOSPITALIZACION ULTIMO MES, dtype: object


In [122]:
print(HospitalOk['PSA'].unique())
#print(HospitalOk['PSA'].value_counts())
print(HospitalOk['PSA'].count())
print(HospitalOk['PSA'].describe())

[  4.     7.7   29.     7.     6.2    6.      nan   5.7    4.3    5.19
   4.5   14.    10.     9.    25.    91.8   21.    98.     7.5   10.8
  10.5   90.     5.1   16.    17.    23.     6.4  100.     5.8   38.9
  20.    40.     9.5    9.6   10.2    8.5   53.    19.     5.6    3.5
  15.     5.2   17.7    4.6    8.     8.7    4.8    7.6   10.6    4.7
  18.    27.     5.     8.39   4.79   6.8    4.9    7.8   16.2    8.3
   6.5    7.2    5.97   6.98  12.    24.     8.9    6.3    9.3   12.6
   5.5   13.8   13.4   11.    21.3    7.1   11.9    3.8   15.6    5.4
  22.    12.8    4.1    2.     9.4    4.49  11.5    5.31  33.6   48.3
   5.11   8.8   26.     0.6   31.    27.6   83.    15.85  20.2   14.9
   2.5    3.9   18.2   28.    33.8   28.6   21.1   30.    13.5    3.
  21.9   43.9    8.1   23.6    3.6    9.9    7.9    6.1    4.4    3.7
  14.5    6.6   12.3    2.4    5.02   7.4    9.7   33.    10.9   76.
  26.6   13.    22.2   22.6   11.7   10.3    6.64  70.     5.3   54.
  45.    35.    15.8  

In [117]:
print(HospitalOk['BIOPSIAS PREVIAS'].unique())
print(HospitalOk['BIOPSIAS PREVIAS'].value_counts())
print(HospitalOk['BIOPSIAS PREVIAS'].count())
print(HospitalOk['BIOPSIAS PREVIAS'].describe())

['NO' 'SI' nan]
BIOPSIAS PREVIAS
NO    510
SI     56
Name: count, dtype: int64
566
count     566
unique      2
top        NO
freq      510
Name: BIOPSIAS PREVIAS, dtype: object


In [116]:
print(HospitalOk['VOLUMEN PROSTATICO'].unique())
print(HospitalOk['VOLUMEN PROSTATICO'].value_counts())
print(HospitalOk['VOLUMEN PROSTATICO'].count())
print(HospitalOk['VOLUMEN PROSTATICO'].describe())

['SI' 'NO' nan]
VOLUMEN PROSTATICO
SI    408
NO    159
Name: count, dtype: int64
567
count     567
unique      2
top        SI
freq      408
Name: VOLUMEN PROSTATICO, dtype: object


In [128]:
print(HospitalOk['ANTIBIOTICO UTILIZADO'].unique())
print(HospitalOk['ANTIBIOTICO UTILIZADO'].value_counts())
print(HospitalOk['ANTIBIOTICO UTILIZADO'].count())
print(HospitalOk['ANTIBIOTICO UTILIZADO'].describe())

['FLUOROQUINOLONA_AMINOGLUCOSIDO' 'CEFALOSPORINA_AMINOGLUCOCIDO'
 'OROQUINOLONAS' 'OTROS']
ANTIBIOTICO UTILIZADO
FLUOROQUINOLONA_AMINOGLUCOSIDO    452
CEFALOSPORINA_AMINOGLUCOCIDO       56
OTROS                              42
OROQUINOLONAS                      18
Name: count, dtype: int64
568
count                                568
unique                                 4
top       FLUOROQUINOLONA_AMINOGLUCOSIDO
freq                                 452
Name: ANTIBIOTICO UTILIZADO, dtype: object


In [127]:
# Detectado Error de Tipeo de 'FLUOROQUINOLONA_AMINOGLUCOSIDO' (se corrige)
HospitalOk.loc[HospitalOk['ANTIBIOTICO UTILIZADO'] == 'FLUOROQUINOLONA_AMINOGLICOSIDO', 'ANTIBIOTICO UTILIZADO'] = 'FLUOROQUINOLONA_AMINOGLUCOSIDO'
HospitalOk.loc[HospitalOk['ANTIBIOTICO UTILIZADO'] == 'FLUOROQUINOLONA_AMINOGLICÓSIDO', 'ANTIBIOTICO UTILIZADO'] = 'FLUOROQUINOLONA_AMINOGLUCOSIDO'

In [130]:
print(HospitalOk['MUESTRAS TOMADAS'].unique())
#print(HospitalOk['MUESTRAS TOMADAS'].value_counts())
print(HospitalOk['MUESTRAS TOMADAS'].count())
print(HospitalOk['MUESTRAS TOMADAS'].describe())

[12. 24. 18.  6. 16. 20. 10.  4.  8. 15. 22. 14.]
568
count    568.000000
mean      12.996479
std        3.921180
min        4.000000
25%       12.000000
50%       12.000000
75%       12.000000
max       24.000000
Name: MUESTRAS TOMADAS, dtype: float64


In [131]:
print(HospitalOk['CUP'].unique())
print(HospitalOk['CUP'].value_counts())
print(HospitalOk['CUP'].count())
print(HospitalOk['CUP'].describe())

['NO' 'SI' nan]
CUP
NO    563
SI      4
Name: count, dtype: int64
567
count     567
unique      2
top        NO
freq      563
Name: CUP, dtype: object


In [132]:
print(HospitalOk['ENFERMEDAD CRONICA PULMONAR OBSTRUCTIVA'].unique())
print(HospitalOk['ENFERMEDAD CRONICA PULMONAR OBSTRUCTIVA'].value_counts())
print(HospitalOk['ENFERMEDAD CRONICA PULMONAR OBSTRUCTIVA'].count())
print(HospitalOk['ENFERMEDAD CRONICA PULMONAR OBSTRUCTIVA'].describe())

# Las categorías se agruparán en SI/NO

['NO' 'SI, EPOC' 'SI, ASMA' 'SI' nan]
ENFERMEDAD CRONICA PULMONAR OBSTRUCTIVA
NO          546
SI           12
SI, EPOC      4
SI, ASMA      4
Name: count, dtype: int64
566
count     566
unique      4
top        NO
freq      546
Name: ENFERMEDAD CRONICA PULMONAR OBSTRUCTIVA, dtype: object


In [133]:
print(HospitalOk['BIOPSIA'].unique())
print(HospitalOk['BIOPSIA'].value_counts())
print(HospitalOk['BIOPSIA'].count())
print(HospitalOk['BIOPSIA'].describe())
# Las categorías podrían agruparse en SI/NO

['NEG' 'ADENOCARCINOMA GLEASON 6 ' 'ADENOCARCINOMA GLEASON 7 '
 'ADENOCARCINOMA GLEASON 6' 'ADENOCARCINOMA GLEASON 10 '
 'ADENOCARCINOMA GLEASON 9 ' 'ADENOCARCINOMA GLEASON 8 ' 'PROSTATITIS'
 'HIPERPLASIA PROSTATICA' 'ADENOCARCINOMA GLEASON 7'
 'CARCINOMA INDIFERENCIADO DE CELULAS CLARAS']
BIOPSIA
NEG                                           322
ADENOCARCINOMA GLEASON 7                      106
ADENOCARCINOMA GLEASON 6                       38
ADENOCARCINOMA GLEASON 8                       22
ADENOCARCINOMA GLEASON 9                       20
ADENOCARCINOMA GLEASON 6                       16
PROSTATITIS                                    14
HIPERPLASIA PROSTATICA                         14
ADENOCARCINOMA GLEASON 7                       10
ADENOCARCINOMA GLEASON 10                       4
CARCINOMA INDIFERENCIADO DE CELULAS CLARAS      2
Name: count, dtype: int64
568
count     568
unique     11
top       NEG
freq      322
Name: BIOPSIA, dtype: object


In [ ]:
# Detectado Error de Tipeo de 'ADENOCARCINOMA GLEASON 6' y 'ADENOCARCINOMA GLEASON 7' (se corrige)
HospitalOk.loc[HospitalOk['BIOPSIA'] == 'ADENOCARCINOMA GLEASON 6 ', 'BIOPSIA'] = 'ADENOCARCINOMA GLEASON 6'
HospitalOk.loc[HospitalOk['BIOPSIA'] == 'ADENOCARCINOMA GLEASON 7 ', 'BIOPSIA'] = 'ADENOCARCINOMA GLEASON 7'

# Se normalizan todos los valores, quitando espacio al final de la cadena
HospitalOk.loc[HospitalOk['BIOPSIA'] == 'ADENOCARCINOMA GLEASON 10 ', 'BIOPSIA'] = 'ADENOCARCINOMA GLEASON 10'
HospitalOk.loc[HospitalOk['BIOPSIA'] == 'ADENOCARCINOMA GLEASON 9 ', 'BIOPSIA'] = 'ADENOCARCINOMA GLEASON 9'
HospitalOk.loc[HospitalOk['BIOPSIA'] == 'ADENOCARCINOMA GLEASON 8 ', 'BIOPSIA'] = 'ADENOCARCINOMA GLEASON 8'

In [134]:
print(HospitalOk['COMPLICACION INFECCIOSA POST BIOPSIA'].unique())
print(HospitalOk['COMPLICACION INFECCIOSA POST BIOPSIA'].value_counts())
print(HospitalOk['COMPLICACION INFECCIOSA POST BIOPSIA'].count())
print(HospitalOk['COMPLICACION INFECCIOSA POST BIOPSIA'].describe())
# Las categorías se agruparán en SI/NO

[1 2 3 5 9 'NO']
COMPLICACION INFECCIOSA POST BIOPSIA
NO    542
2       9
3       8
1       5
5       2
9       2
Name: count, dtype: int64
568
count     568
unique      6
top        NO
freq      542
Name: COMPLICACION INFECCIOSA POST BIOPSIA, dtype: object


In [135]:
print(HospitalOk['FIEBRE'].unique())
print(HospitalOk['FIEBRE'].value_counts())
print(HospitalOk['FIEBRE'].count())
print(HospitalOk['FIEBRE'].describe())

['SI' 'NO']
FIEBRE
NO    531
SI     37
Name: count, dtype: int64
568
count     568
unique      2
top        NO
freq      531
Name: FIEBRE, dtype: object


In [136]:
print(HospitalOk['ITU'].unique())
print(HospitalOk['ITU'].value_counts())
print(HospitalOk['ITU'].count())
print(HospitalOk['ITU'].describe())

['NO' 'SI']
ITU
NO    562
SI      6
Name: count, dtype: int64
568
count     568
unique      2
top        NO
freq      562
Name: ITU, dtype: object


In [137]:
print(HospitalOk['TIPO DE CULTIVO'].unique())
print(HospitalOk['TIPO DE CULTIVO'].value_counts())
print(HospitalOk['TIPO DE CULTIVO'].count())
print(HospitalOk['TIPO DE CULTIVO'].describe())

# Las categorías podrían agruparse en SI/NO

['NO' 'HEMOCULTIVO' 'UROCULTIVO' 'HEMOCULTIVO Y UROCULTIVO']
TIPO DE CULTIVO
NO                          560
UROCULTIVO                    4
HEMOCULTIVO                   2
HEMOCULTIVO Y UROCULTIVO      2
Name: count, dtype: int64
568
count     568
unique      4
top        NO
freq      560
Name: TIPO DE CULTIVO, dtype: object


In [138]:
print(HospitalOk['AGENTE AISLADO'].unique())
print(HospitalOk['AGENTE AISLADO'].value_counts())
print(HospitalOk['AGENTE AISLADO'].count())
print(HospitalOk['AGENTE AISLADO'].describe())

# Las categorías podrían agruparse en SI/NO

['NO' 'E.COLI' 'PSEUDOMONAS AERUGINOSA' nan]
AGENTE AISLADO
NO                        543
E.COLI                      6
PSEUDOMONAS AERUGINOSA      2
Name: count, dtype: int64
551
count     551
unique      3
top        NO
freq      543
Name: AGENTE AISLADO, dtype: object


In [139]:
print(HospitalOk['PATRON DE RESISTENCIA'].unique())
print(HospitalOk['PATRON DE RESISTENCIA'].value_counts())
print(HospitalOk['PATRON DE RESISTENCIA'].count())
print(HospitalOk['PATRON DE RESISTENCIA'].describe())

# Las categorías podrían agruparse en SI/NO

['NO' ' AMPI R, CIPRO R, GENTA R, SULFA M R'
 'RESISTENTE A AMPI, CIPRO Y GENTA'
 'RESISTENTE A AMPI, SULFA, CEFADROXILO, CEFUROXIMO, CIPRO Y CEFEPIME, CEFOTAXIMA'
 'MULTI SENSIBLE']
PATRON DE RESISTENCIA
NO                                                                                 561
RESISTENTE A AMPI, CIPRO Y GENTA                                                     2
RESISTENTE A AMPI, SULFA, CEFADROXILO, CEFUROXIMO, CIPRO Y CEFEPIME, CEFOTAXIMA      2
MULTI SENSIBLE                                                                       2
 AMPI R, CIPRO R, GENTA R, SULFA M R                                                 1
Name: count, dtype: int64
568
count     568
unique      5
top        NO
freq      561
Name: PATRON DE RESISTENCIA, dtype: object


In [140]:
print(HospitalOk['HOSPITALIZACION'].unique())
print(HospitalOk['HOSPITALIZACION'].value_counts())
print(HospitalOk['HOSPITALIZACION'].count())
print(HospitalOk['HOSPITALIZACION'].describe())

['SI' 'NO' nan]
HOSPITALIZACION
NO    541
SI     24
Name: count, dtype: int64
565
count     565
unique      2
top        NO
freq      541
Name: HOSPITALIZACION, dtype: object


In [141]:
print(HospitalOk['DIAS HOSPITALIZACION MQ'].unique())
print(HospitalOk['DIAS HOSPITALIZACION MQ'].value_counts())
print(HospitalOk['DIAS HOSPITALIZACION MQ'].count())
print(HospitalOk['DIAS HOSPITALIZACION MQ'].describe())

# Esta columna será eliminada

[ 2.  5.  4.  3. 12.  0.]
DIAS HOSPITALIZACION MQ
0.0     544
2.0       8
4.0       6
3.0       5
5.0       3
12.0      2
Name: count, dtype: int64
568
count    568.000000
mean       0.165493
std        0.958066
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       12.000000
Name: DIAS HOSPITALIZACION MQ, dtype: float64


In [142]:
print(HospitalOk['DIAS HOSPITALIZACION UPC'].unique())
print(HospitalOk['DIAS HOSPITALIZACION UPC'].value_counts())
print(HospitalOk['DIAS HOSPITALIZACION UPC'].count())
print(HospitalOk['DIAS HOSPITALIZACION UPC'].describe())

# Esta columna será eliminada

[0. 3. 2.]
DIAS HOSPITALIZACION UPC
0.0    565
3.0      2
2.0      1
Name: count, dtype: int64
568
count    568.000000
mean       0.014085
std        0.196474
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        3.000000
Name: DIAS HOSPITALIZACION UPC, dtype: float64


# Luego del EDA exportamos el DataFrame como un nuevo archivo Excel

In [143]:
HospitalOk.to_excel(r'C:\Users\Usuario\proyectos PY\SOY HENRY\Bootcamp\M6\Proyecto Integrador\Propuesta 1\HospitalOk.xlsx', index=False)